// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum ImageFormatWire: Int, CaseIterable {
  case jpeg = 0
  case png = 1
  case webp = 2
  case heic = 3
}

enum ExifPolicyWire: Int, CaseIterable {
  case keep = 0
  case strip = 1
}

enum QualityPresetWire: Int, CaseIterable {
  case veryLow = 0
  case low = 1
  case medium = 2
  case high = 3
  case veryHigh = 4
  case custom = 5
}

enum VideoCodecWire: Int, CaseIterable {
  case h264 = 0
  case hevc = 1
  case auto = 2
}

enum CompressionModeWire: Int, CaseIterable {
  case manual = 0
  case smart = 1
}

enum MediaTypeWire: Int, CaseIterable {
  case image = 0
  case video = 1
  case unknown = 2
}

enum CodecSupportStatusWire: Int, CaseIterable {
  case supported = 0
  case unsupported = 1
  case unknown = 2
}

enum CompressionStageWire: Int, CaseIterable {
  case preparing = 0
  case analyzing = 1
  case decoding = 2
  case encoding = 3
  case muxing = 4
  case finalizing = 5
  case completed = 6
  case failed = 7
  case cancelled = 8
}

enum TaskOutcomeWire: Int, CaseIterable {
  case completed = 0
  case failed = 1
  case cancelled = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImageCompressRequest: Hashable, CustomStringConvertible {
  var taskId: String
  var sourcePath: String
  var outputPath: String? = nil
  var format: ImageFormatWire? = nil
  var quality: Int64
  var maxWidth: Int64? = nil
  var maxHeight: Int64? = nil
  var rotationDegrees: Int64
  var exifPolicy: ExifPolicyWire
  var targetSizeBytes: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageCompressRequest? {
    let taskId = pigeonVar_list[0] as! String
    let sourcePath = pigeonVar_list[1] as! String
    let outputPath: String? = nilOrValue(pigeonVar_list[2])
    let format: ImageFormatWire? = nilOrValue(pigeonVar_list[3])
    let quality = pigeonVar_list[4] as! Int64
    let maxWidth: Int64? = nilOrValue(pigeonVar_list[5])
    let maxHeight: Int64? = nilOrValue(pigeonVar_list[6])
    let rotationDegrees = pigeonVar_list[7] as! Int64
    let exifPolicy = pigeonVar_list[8] as! ExifPolicyWire
    let targetSizeBytes: Int64? = nilOrValue(pigeonVar_list[9])

    return ImageCompressRequest(
      taskId: taskId,
      sourcePath: sourcePath,
      outputPath: outputPath,
      format: format,
      quality: quality,
      maxWidth: maxWidth,
      maxHeight: maxHeight,
      rotationDegrees: rotationDegrees,
      exifPolicy: exifPolicy,
      targetSizeBytes: targetSizeBytes
    )
  }
  func toList() -> [Any?] {
    return [
      taskId,
      sourcePath,
      outputPath,
      format,
      quality,
      maxWidth,
      maxHeight,
      rotationDegrees,
      exifPolicy,
      targetSizeBytes,
    ]
  }
  static func == (lhs: ImageCompressRequest, rhs: ImageCompressRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.taskId, rhs.taskId) && MessagesPigeonInternal.deepEquals(lhs.sourcePath, rhs.sourcePath) && MessagesPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.quality, rhs.quality) && MessagesPigeonInternal.deepEquals(lhs.maxWidth, rhs.maxWidth) && MessagesPigeonInternal.deepEquals(lhs.maxHeight, rhs.maxHeight) && MessagesPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && MessagesPigeonInternal.deepEquals(lhs.exifPolicy, rhs.exifPolicy) && MessagesPigeonInternal.deepEquals(lhs.targetSizeBytes, rhs.targetSizeBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageCompressRequest")
    MessagesPigeonInternal.deepHash(value: taskId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourcePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: quality, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: exifPolicy, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: targetSizeBytes, hasher: &hasher)
  }

  public var description: String {
    return "ImageCompressRequest(taskId: \(String(describing: taskId)), sourcePath: \(String(describing: sourcePath)), outputPath: \(String(describing: outputPath)), format: \(String(describing: format)), quality: \(String(describing: quality)), maxWidth: \(String(describing: maxWidth)), maxHeight: \(String(describing: maxHeight)), rotationDegrees: \(String(describing: rotationDegrees)), exifPolicy: \(String(describing: exifPolicy)), targetSizeBytes: \(String(describing: targetSizeBytes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoCompressRequest: Hashable, CustomStringConvertible {
  var taskId: String
  var sourcePath: String
  var outputPath: String? = nil
  var preset: QualityPresetWire? = nil
  var codec: VideoCodecWire? = nil
  var maxWidth: Int64? = nil
  var maxHeight: Int64? = nil
  var fps: Int64? = nil
  var bitrateBps: Int64? = nil
  var audioEnabled: Bool
  var audioBitrateBps: Int64? = nil
  var trimStartMs: Int64? = nil
  var trimEndMs: Int64? = nil
  var rotationDegrees: Int64
  var targetSizeBytes: Int64? = nil
  var mode: CompressionModeWire


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoCompressRequest? {
    let taskId = pigeonVar_list[0] as! String
    let sourcePath = pigeonVar_list[1] as! String
    let outputPath: String? = nilOrValue(pigeonVar_list[2])
    let preset: QualityPresetWire? = nilOrValue(pigeonVar_list[3])
    let codec: VideoCodecWire? = nilOrValue(pigeonVar_list[4])
    let maxWidth: Int64? = nilOrValue(pigeonVar_list[5])
    let maxHeight: Int64? = nilOrValue(pigeonVar_list[6])
    let fps: Int64? = nilOrValue(pigeonVar_list[7])
    let bitrateBps: Int64? = nilOrValue(pigeonVar_list[8])
    let audioEnabled = pigeonVar_list[9] as! Bool
    let audioBitrateBps: Int64? = nilOrValue(pigeonVar_list[10])
    let trimStartMs: Int64? = nilOrValue(pigeonVar_list[11])
    let trimEndMs: Int64? = nilOrValue(pigeonVar_list[12])
    let rotationDegrees = pigeonVar_list[13] as! Int64
    let targetSizeBytes: Int64? = nilOrValue(pigeonVar_list[14])
    let mode = pigeonVar_list[15] as! CompressionModeWire

    return VideoCompressRequest(
      taskId: taskId,
      sourcePath: sourcePath,
      outputPath: outputPath,
      preset: preset,
      codec: codec,
      maxWidth: maxWidth,
      maxHeight: maxHeight,
      fps: fps,
      bitrateBps: bitrateBps,
      audioEnabled: audioEnabled,
      audioBitrateBps: audioBitrateBps,
      trimStartMs: trimStartMs,
      trimEndMs: trimEndMs,
      rotationDegrees: rotationDegrees,
      targetSizeBytes: targetSizeBytes,
      mode: mode
    )
  }
  func toList() -> [Any?] {
    return [
      taskId,
      sourcePath,
      outputPath,
      preset,
      codec,
      maxWidth,
      maxHeight,
      fps,
      bitrateBps,
      audioEnabled,
      audioBitrateBps,
      trimStartMs,
      trimEndMs,
      rotationDegrees,
      targetSizeBytes,
      mode,
    ]
  }
  static func == (lhs: VideoCompressRequest, rhs: VideoCompressRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.taskId, rhs.taskId) && MessagesPigeonInternal.deepEquals(lhs.sourcePath, rhs.sourcePath) && MessagesPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && MessagesPigeonInternal.deepEquals(lhs.preset, rhs.preset) && MessagesPigeonInternal.deepEquals(lhs.codec, rhs.codec) && MessagesPigeonInternal.deepEquals(lhs.maxWidth, rhs.maxWidth) && MessagesPigeonInternal.deepEquals(lhs.maxHeight, rhs.maxHeight) && MessagesPigeonInternal.deepEquals(lhs.fps, rhs.fps) && MessagesPigeonInternal.deepEquals(lhs.bitrateBps, rhs.bitrateBps) && MessagesPigeonInternal.deepEquals(lhs.audioEnabled, rhs.audioEnabled) && MessagesPigeonInternal.deepEquals(lhs.audioBitrateBps, rhs.audioBitrateBps) && MessagesPigeonInternal.deepEquals(lhs.trimStartMs, rhs.trimStartMs) && MessagesPigeonInternal.deepEquals(lhs.trimEndMs, rhs.trimEndMs) && MessagesPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && MessagesPigeonInternal.deepEquals(lhs.targetSizeBytes, rhs.targetSizeBytes) && MessagesPigeonInternal.deepEquals(lhs.mode, rhs.mode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoCompressRequest")
    MessagesPigeonInternal.deepHash(value: taskId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourcePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: preset, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: codec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitrateBps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioBitrateBps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: trimStartMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: trimEndMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: targetSizeBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mode, hasher: &hasher)
  }

  public var description: String {
    return "VideoCompressRequest(taskId: \(String(describing: taskId)), sourcePath: \(String(describing: sourcePath)), outputPath: \(String(describing: outputPath)), preset: \(String(describing: preset)), codec: \(String(describing: codec)), maxWidth: \(String(describing: maxWidth)), maxHeight: \(String(describing: maxHeight)), fps: \(String(describing: fps)), bitrateBps: \(String(describing: bitrateBps)), audioEnabled: \(String(describing: audioEnabled)), audioBitrateBps: \(String(describing: audioBitrateBps)), trimStartMs: \(String(describing: trimStartMs)), trimEndMs: \(String(describing: trimEndMs)), rotationDegrees: \(String(describing: rotationDegrees)), targetSizeBytes: \(String(describing: targetSizeBytes)), mode: \(String(describing: mode)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ThumbnailRequest: Hashable, CustomStringConvertible {
  var taskId: String
  var sourcePath: String
  /// Validated Dart-side (against the source's real duration, from a
  /// [MediaInfoRequest] pre-check) before this ever reaches native code —
  /// out-of-range positions throw `InvalidMediaException` in Dart rather
  /// than being handled by native bounds-checking.
  var positionsMs: [Int64]
  var maxWidth: Int64
  var maxHeight: Int64
  var format: ImageFormatWire
  var quality: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ThumbnailRequest? {
    let taskId = pigeonVar_list[0] as! String
    let sourcePath = pigeonVar_list[1] as! String
    let positionsMs = pigeonVar_list[2] as! [Int64]
    let maxWidth = pigeonVar_list[3] as! Int64
    let maxHeight = pigeonVar_list[4] as! Int64
    let format = pigeonVar_list[5] as! ImageFormatWire
    let quality = pigeonVar_list[6] as! Int64

    return ThumbnailRequest(
      taskId: taskId,
      sourcePath: sourcePath,
      positionsMs: positionsMs,
      maxWidth: maxWidth,
      maxHeight: maxHeight,
      format: format,
      quality: quality
    )
  }
  func toList() -> [Any?] {
    return [
      taskId,
      sourcePath,
      positionsMs,
      maxWidth,
      maxHeight,
      format,
      quality,
    ]
  }
  static func == (lhs: ThumbnailRequest, rhs: ThumbnailRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.taskId, rhs.taskId) && MessagesPigeonInternal.deepEquals(lhs.sourcePath, rhs.sourcePath) && MessagesPigeonInternal.deepEquals(lhs.positionsMs, rhs.positionsMs) && MessagesPigeonInternal.deepEquals(lhs.maxWidth, rhs.maxWidth) && MessagesPigeonInternal.deepEquals(lhs.maxHeight, rhs.maxHeight) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.quality, rhs.quality)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ThumbnailRequest")
    MessagesPigeonInternal.deepHash(value: taskId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sourcePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: positionsMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxHeight, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: quality, hasher: &hasher)
  }

  public var description: String {
    return "ThumbnailRequest(taskId: \(String(describing: taskId)), sourcePath: \(String(describing: sourcePath)), positionsMs: \(String(describing: positionsMs)), maxWidth: \(String(describing: maxWidth)), maxHeight: \(String(describing: maxHeight)), format: \(String(describing: format)), quality: \(String(describing: quality)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfoRequest: Hashable, CustomStringConvertible {
  var sourcePath: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfoRequest? {
    let sourcePath = pigeonVar_list[0] as! String

    return MediaInfoRequest(
      sourcePath: sourcePath
    )
  }
  func toList() -> [Any?] {
    return [
      sourcePath
    ]
  }
  static func == (lhs: MediaInfoRequest, rhs: MediaInfoRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sourcePath, rhs.sourcePath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaInfoRequest")
    MessagesPigeonInternal.deepHash(value: sourcePath, hasher: &hasher)
  }

  public var description: String {
    return "MediaInfoRequest(sourcePath: \(String(describing: sourcePath)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CompressionResultMessage: Hashable, CustomStringConvertible {
  var outputPath: String
  var originalSizeBytes: Int64
  var outputSizeBytes: Int64
  var compressionRatio: Double
  var durationMs: Int64
  var codec: String
  var format: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CompressionResultMessage? {
    let outputPath = pigeonVar_list[0] as! String
    let originalSizeBytes = pigeonVar_list[1] as! Int64
    let outputSizeBytes = pigeonVar_list[2] as! Int64
    let compressionRatio = pigeonVar_list[3] as! Double
    let durationMs = pigeonVar_list[4] as! Int64
    let codec = pigeonVar_list[5] as! String
    let format = pigeonVar_list[6] as! String

    return CompressionResultMessage(
      outputPath: outputPath,
      originalSizeBytes: originalSizeBytes,
      outputSizeBytes: outputSizeBytes,
      compressionRatio: compressionRatio,
      durationMs: durationMs,
      codec: codec,
      format: format
    )
  }
  func toList() -> [Any?] {
    return [
      outputPath,
      originalSizeBytes,
      outputSizeBytes,
      compressionRatio,
      durationMs,
      codec,
      format,
    ]
  }
  static func == (lhs: CompressionResultMessage, rhs: CompressionResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && MessagesPigeonInternal.deepEquals(lhs.originalSizeBytes, rhs.originalSizeBytes) && MessagesPigeonInternal.deepEquals(lhs.outputSizeBytes, rhs.outputSizeBytes) && MessagesPigeonInternal.deepEquals(lhs.compressionRatio, rhs.compressionRatio) && MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.codec, rhs.codec) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CompressionResultMessage")
    MessagesPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: originalSizeBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputSizeBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: compressionRatio, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: codec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
  }

  public var description: String {
    return "CompressionResultMessage(outputPath: \(String(describing: outputPath)), originalSizeBytes: \(String(describing: originalSizeBytes)), outputSizeBytes: \(String(describing: outputSizeBytes)), compressionRatio: \(String(describing: compressionRatio)), durationMs: \(String(describing: durationMs)), codec: \(String(describing: codec)), format: \(String(describing: format)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ThumbnailResultMessage: Hashable, CustomStringConvertible {
  var outputPath: String
  var positionMs: Int64
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ThumbnailResultMessage? {
    let outputPath = pigeonVar_list[0] as! String
    let positionMs = pigeonVar_list[1] as! Int64
    let width = pigeonVar_list[2] as! Int64
    let height = pigeonVar_list[3] as! Int64

    return ThumbnailResultMessage(
      outputPath: outputPath,
      positionMs: positionMs,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      outputPath,
      positionMs,
      width,
      height,
    ]
  }
  static func == (lhs: ThumbnailResultMessage, rhs: ThumbnailResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && MessagesPigeonInternal.deepEquals(lhs.positionMs, rhs.positionMs) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ThumbnailResultMessage")
    MessagesPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: positionMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "ThumbnailResultMessage(outputPath: \(String(describing: outputPath)), positionMs: \(String(describing: positionMs)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfoMessage: Hashable, CustomStringConvertible {
  var mediaType: MediaTypeWire
  var width: Int64? = nil
  var height: Int64? = nil
  var format: String? = nil
  var sizeBytes: Int64
  var exifPresent: Bool? = nil
  var orientation: Int64? = nil
  var durationMs: Int64? = nil
  var fps: Double? = nil
  var bitrateBps: Int64? = nil
  var videoCodec: String? = nil
  var audioCodec: String? = nil
  var container: String? = nil
  var hasAudio: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfoMessage? {
    let mediaType = pigeonVar_list[0] as! MediaTypeWire
    let width: Int64? = nilOrValue(pigeonVar_list[1])
    let height: Int64? = nilOrValue(pigeonVar_list[2])
    let format: String? = nilOrValue(pigeonVar_list[3])
    let sizeBytes = pigeonVar_list[4] as! Int64
    let exifPresent: Bool? = nilOrValue(pigeonVar_list[5])
    let orientation: Int64? = nilOrValue(pigeonVar_list[6])
    let durationMs: Int64? = nilOrValue(pigeonVar_list[7])
    let fps: Double? = nilOrValue(pigeonVar_list[8])
    let bitrateBps: Int64? = nilOrValue(pigeonVar_list[9])
    let videoCodec: String? = nilOrValue(pigeonVar_list[10])
    let audioCodec: String? = nilOrValue(pigeonVar_list[11])
    let container: String? = nilOrValue(pigeonVar_list[12])
    let hasAudio: Bool? = nilOrValue(pigeonVar_list[13])

    return MediaInfoMessage(
      mediaType: mediaType,
      width: width,
      height: height,
      format: format,
      sizeBytes: sizeBytes,
      exifPresent: exifPresent,
      orientation: orientation,
      durationMs: durationMs,
      fps: fps,
      bitrateBps: bitrateBps,
      videoCodec: videoCodec,
      audioCodec: audioCodec,
      container: container,
      hasAudio: hasAudio
    )
  }
  func toList() -> [Any?] {
    return [
      mediaType,
      width,
      height,
      format,
      sizeBytes,
      exifPresent,
      orientation,
      durationMs,
      fps,
      bitrateBps,
      videoCodec,
      audioCodec,
      container,
      hasAudio,
    ]
  }
  static func == (lhs: MediaInfoMessage, rhs: MediaInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.mediaType, rhs.mediaType) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.sizeBytes, rhs.sizeBytes) && MessagesPigeonInternal.deepEquals(lhs.exifPresent, rhs.exifPresent) && MessagesPigeonInternal.deepEquals(lhs.orientation, rhs.orientation) && MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.fps, rhs.fps) && MessagesPigeonInternal.deepEquals(lhs.bitrateBps, rhs.bitrateBps) && MessagesPigeonInternal.deepEquals(lhs.videoCodec, rhs.videoCodec) && MessagesPigeonInternal.deepEquals(lhs.audioCodec, rhs.audioCodec) && MessagesPigeonInternal.deepEquals(lhs.container, rhs.container) && MessagesPigeonInternal.deepEquals(lhs.hasAudio, rhs.hasAudio)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaInfoMessage")
    MessagesPigeonInternal.deepHash(value: mediaType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sizeBytes, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: exifPresent, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: orientation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitrateBps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: videoCodec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audioCodec, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: container, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasAudio, hasher: &hasher)
  }

  public var description: String {
    return "MediaInfoMessage(mediaType: \(String(describing: mediaType)), width: \(String(describing: width)), height: \(String(describing: height)), format: \(String(describing: format)), sizeBytes: \(String(describing: sizeBytes)), exifPresent: \(String(describing: exifPresent)), orientation: \(String(describing: orientation)), durationMs: \(String(describing: durationMs)), fps: \(String(describing: fps)), bitrateBps: \(String(describing: bitrateBps)), videoCodec: \(String(describing: videoCodec)), audioCodec: \(String(describing: audioCodec)), container: \(String(describing: container)), hasAudio: \(String(describing: hasAudio)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CapabilitiesReportMessage: Hashable, CustomStringConvertible {
  var h264Encode: CodecSupportStatusWire
  var hevcEncode: CodecSupportStatusWire
  var aacEncode: CodecSupportStatusWire
  var webpEncode: CodecSupportStatusWire
  var heicEncode: CodecSupportStatusWire
  var maxHardwareWidth: Int64? = nil
  var maxHardwareHeight: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CapabilitiesReportMessage? {
    let h264Encode = pigeonVar_list[0] as! CodecSupportStatusWire
    let hevcEncode = pigeonVar_list[1] as! CodecSupportStatusWire
    let aacEncode = pigeonVar_list[2] as! CodecSupportStatusWire
    let webpEncode = pigeonVar_list[3] as! CodecSupportStatusWire
    let heicEncode = pigeonVar_list[4] as! CodecSupportStatusWire
    let maxHardwareWidth: Int64? = nilOrValue(pigeonVar_list[5])
    let maxHardwareHeight: Int64? = nilOrValue(pigeonVar_list[6])

    return CapabilitiesReportMessage(
      h264Encode: h264Encode,
      hevcEncode: hevcEncode,
      aacEncode: aacEncode,
      webpEncode: webpEncode,
      heicEncode: heicEncode,
      maxHardwareWidth: maxHardwareWidth,
      maxHardwareHeight: maxHardwareHeight
    )
  }
  func toList() -> [Any?] {
    return [
      h264Encode,
      hevcEncode,
      aacEncode,
      webpEncode,
      heicEncode,
      maxHardwareWidth,
      maxHardwareHeight,
    ]
  }
  static func == (lhs: CapabilitiesReportMessage, rhs: CapabilitiesReportMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.h264Encode, rhs.h264Encode) && MessagesPigeonInternal.deepEquals(lhs.hevcEncode, rhs.hevcEncode) && MessagesPigeonInternal.deepEquals(lhs.aacEncode, rhs.aacEncode) && MessagesPigeonInternal.deepEquals(lhs.webpEncode, rhs.webpEncode) && MessagesPigeonInternal.deepEquals(lhs.heicEncode, rhs.heicEncode) && MessagesPigeonInternal.deepEquals(lhs.maxHardwareWidth, rhs.maxHardwareWidth) && MessagesPigeonInternal.deepEquals(lhs.maxHardwareHeight, rhs.maxHardwareHeight)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CapabilitiesReportMessage")
    MessagesPigeonInternal.deepHash(value: h264Encode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hevcEncode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: aacEncode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: webpEncode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: heicEncode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxHardwareWidth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxHardwareHeight, hasher: &hasher)
  }

  public var description: String {
    return "CapabilitiesReportMessage(h264Encode: \(String(describing: h264Encode)), hevcEncode: \(String(describing: hevcEncode)), aacEncode: \(String(describing: aacEncode)), webpEncode: \(String(describing: webpEncode)), heicEncode: \(String(describing: heicEncode)), maxHardwareWidth: \(String(describing: maxHardwareWidth)), maxHardwareHeight: \(String(describing: maxHardwareHeight)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProgressEventMessage: Hashable, CustomStringConvertible {
  var taskId: String
  var stage: CompressionStageWire
  var percent: Double
  var currentItemIndex: Int64? = nil
  var totalItems: Int64? = nil
  var note: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProgressEventMessage? {
    let taskId = pigeonVar_list[0] as! String
    let stage = pigeonVar_list[1] as! CompressionStageWire
    let percent = pigeonVar_list[2] as! Double
    let currentItemIndex: Int64? = nilOrValue(pigeonVar_list[3])
    let totalItems: Int64? = nilOrValue(pigeonVar_list[4])
    let note: String? = nilOrValue(pigeonVar_list[5])

    return ProgressEventMessage(
      taskId: taskId,
      stage: stage,
      percent: percent,
      currentItemIndex: currentItemIndex,
      totalItems: totalItems,
      note: note
    )
  }
  func toList() -> [Any?] {
    return [
      taskId,
      stage,
      percent,
      currentItemIndex,
      totalItems,
      note,
    ]
  }
  static func == (lhs: ProgressEventMessage, rhs: ProgressEventMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.taskId, rhs.taskId) && MessagesPigeonInternal.deepEquals(lhs.stage, rhs.stage) && MessagesPigeonInternal.deepEquals(lhs.percent, rhs.percent) && MessagesPigeonInternal.deepEquals(lhs.currentItemIndex, rhs.currentItemIndex) && MessagesPigeonInternal.deepEquals(lhs.totalItems, rhs.totalItems) && MessagesPigeonInternal.deepEquals(lhs.note, rhs.note)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProgressEventMessage")
    MessagesPigeonInternal.deepHash(value: taskId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: percent, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: currentItemIndex, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: totalItems, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: note, hasher: &hasher)
  }

  public var description: String {
    return "ProgressEventMessage(taskId: \(String(describing: taskId)), stage: \(String(describing: stage)), percent: \(String(describing: percent)), currentItemIndex: \(String(describing: currentItemIndex)), totalItems: \(String(describing: totalItems)), note: \(String(describing: note)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TaskTerminalMessage: Hashable, CustomStringConvertible {
  var taskId: String
  var outcome: TaskOutcomeWire
  var result: CompressionResultMessage? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TaskTerminalMessage? {
    let taskId = pigeonVar_list[0] as! String
    let outcome = pigeonVar_list[1] as! TaskOutcomeWire
    let result: CompressionResultMessage? = nilOrValue(pigeonVar_list[2])
    let errorCode: String? = nilOrValue(pigeonVar_list[3])
    let errorMessage: String? = nilOrValue(pigeonVar_list[4])

    return TaskTerminalMessage(
      taskId: taskId,
      outcome: outcome,
      result: result,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      taskId,
      outcome,
      result,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: TaskTerminalMessage, rhs: TaskTerminalMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.taskId, rhs.taskId) && MessagesPigeonInternal.deepEquals(lhs.outcome, rhs.outcome) && MessagesPigeonInternal.deepEquals(lhs.result, rhs.result) && MessagesPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && MessagesPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TaskTerminalMessage")
    MessagesPigeonInternal.deepHash(value: taskId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outcome, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: result, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "TaskTerminalMessage(taskId: \(String(describing: taskId)), outcome: \(String(describing: outcome)), result: \(String(describing: result)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ImageFormatWire(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ExifPolicyWire(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return QualityPresetWire(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VideoCodecWire(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CompressionModeWire(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MediaTypeWire(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CodecSupportStatusWire(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CompressionStageWire(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TaskOutcomeWire(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      return ImageCompressRequest.fromList(self.readValue() as! [Any?])
    case 139:
      return VideoCompressRequest.fromList(self.readValue() as! [Any?])
    case 140:
      return ThumbnailRequest.fromList(self.readValue() as! [Any?])
    case 141:
      return MediaInfoRequest.fromList(self.readValue() as! [Any?])
    case 142:
      return CompressionResultMessage.fromList(self.readValue() as! [Any?])
    case 143:
      return ThumbnailResultMessage.fromList(self.readValue() as! [Any?])
    case 144:
      return MediaInfoMessage.fromList(self.readValue() as! [Any?])
    case 145:
      return CapabilitiesReportMessage.fromList(self.readValue() as! [Any?])
    case 146:
      return ProgressEventMessage.fromList(self.readValue() as! [Any?])
    case 147:
      return TaskTerminalMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ImageFormatWire {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ExifPolicyWire {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? QualityPresetWire {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? VideoCodecWire {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? CompressionModeWire {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? MediaTypeWire {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? CodecSupportStatusWire {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? CompressionStageWire {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? TaskOutcomeWire {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? ImageCompressRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? VideoCompressRequest {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ThumbnailRequest {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? MediaInfoRequest {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? CompressionResultMessage {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? ThumbnailResultMessage {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? MediaInfoMessage {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? CapabilitiesReportMessage {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? ProgressEventMessage {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? TaskTerminalMessage {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ImageHostApi {
  func compressImage(request: ImageCompressRequest, completion: @escaping (Result<CompressionResultMessage, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ImageHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ImageHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ImageHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let compressImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.ImageHostApi.compressImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compressImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ImageCompressRequest
        api.compressImage(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compressImageChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VideoHostApi {
  func compressVideo(request: VideoCompressRequest, completion: @escaping (Result<CompressionResultMessage, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VideoHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VideoHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VideoHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let compressVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.VideoHostApi.compressVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      compressVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VideoCompressRequest
        api.compressVideo(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      compressVideoChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ThumbnailHostApi {
  func generateThumbnails(request: ThumbnailRequest, completion: @escaping (Result<[ThumbnailResultMessage], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ThumbnailHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ThumbnailHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ThumbnailHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let generateThumbnailsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.ThumbnailHostApi.generateThumbnails\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateThumbnailsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ThumbnailRequest
        api.generateThumbnails(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateThumbnailsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MetadataHostApi {
  func getMediaInfo(request: MediaInfoRequest, completion: @escaping (Result<MediaInfoMessage, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MetadataHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MetadataHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MetadataHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getMediaInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.MetadataHostApi.getMediaInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMediaInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! MediaInfoRequest
        api.getMediaInfo(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMediaInfoChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CapabilityHostApi {
  func capabilities(completion: @escaping (Result<CapabilitiesReportMessage, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CapabilityHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CapabilityHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CapabilityHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let capabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.CapabilityHostApi.capabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      capabilitiesChannel.setMessageHandler { _, reply in
        api.capabilities { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      capabilitiesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CacheHostApi {
  func clearCache(completion: @escaping (Result<Void, Error>) -> Void)
  func getCacheSize(completion: @escaping (Result<Int64, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CacheHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `CacheHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CacheHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let clearCacheChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.CacheHostApi.clearCache\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearCacheChannel.setMessageHandler { _, reply in
        api.clearCache { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearCacheChannel.setMessageHandler(nil)
    }
    let getCacheSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.CacheHostApi.getCacheSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCacheSizeChannel.setMessageHandler { _, reply in
        api.getCacheSize { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCacheSizeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TaskHostApi {
  func cancel(taskId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func cancelAll(completion: @escaping (Result<Void, Error>) -> Void)
  func activeTaskIds(completion: @escaping (Result<[String], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TaskHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `TaskHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TaskHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.TaskHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        api.cancel(taskId: taskIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
    let cancelAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.TaskHostApi.cancelAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAllChannel.setMessageHandler { _, reply in
        api.cancelAll { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelAllChannel.setMessageHandler(nil)
    }
    let activeTaskIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pixel_compressor.TaskHostApi.activeTaskIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      activeTaskIdsChannel.setMessageHandler { _, reply in
        api.activeTaskIds { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      activeTaskIdsChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PixelCompressorProgressCallbackApiProtocol {
  func onProgress(event eventArg: ProgressEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onTaskTerminal(message messageArg: TaskTerminalMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PixelCompressorProgressCallbackApi: PixelCompressorProgressCallbackApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onProgress(event eventArg: ProgressEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pixel_compressor.PixelCompressorProgressCallbackApi.onProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onTaskTerminal(message messageArg: TaskTerminalMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pixel_compressor.PixelCompressorProgressCallbackApi.onTaskTerminal\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
