// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.therivanta.pixelcompressor

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class ImageFormatWire(val raw: Int) {
  JPEG(0),
  PNG(1),
  WEBP(2),
  HEIC(3);

  companion object {
    fun ofRaw(raw: Int): ImageFormatWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ExifPolicyWire(val raw: Int) {
  KEEP(0),
  STRIP(1);

  companion object {
    fun ofRaw(raw: Int): ExifPolicyWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class QualityPresetWire(val raw: Int) {
  VERY_LOW(0),
  LOW(1),
  MEDIUM(2),
  HIGH(3),
  VERY_HIGH(4),
  CUSTOM(5);

  companion object {
    fun ofRaw(raw: Int): QualityPresetWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VideoCodecWire(val raw: Int) {
  H264(0),
  HEVC(1),
  AUTO(2);

  companion object {
    fun ofRaw(raw: Int): VideoCodecWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CompressionModeWire(val raw: Int) {
  MANUAL(0),
  SMART(1);

  companion object {
    fun ofRaw(raw: Int): CompressionModeWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaTypeWire(val raw: Int) {
  IMAGE(0),
  VIDEO(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): MediaTypeWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CodecSupportStatusWire(val raw: Int) {
  SUPPORTED(0),
  UNSUPPORTED(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): CodecSupportStatusWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CompressionStageWire(val raw: Int) {
  PREPARING(0),
  ANALYZING(1),
  DECODING(2),
  ENCODING(3),
  MUXING(4),
  FINALIZING(5),
  COMPLETED(6),
  FAILED(7),
  CANCELLED(8);

  companion object {
    fun ofRaw(raw: Int): CompressionStageWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class TaskOutcomeWire(val raw: Int) {
  COMPLETED(0),
  FAILED(1),
  CANCELLED(2);

  companion object {
    fun ofRaw(raw: Int): TaskOutcomeWire? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ImageCompressRequest (
  val taskId: String,
  val sourcePath: String,
  val outputPath: String? = null,
  val format: ImageFormatWire? = null,
  val quality: Long,
  val maxWidth: Long? = null,
  val maxHeight: Long? = null,
  val rotationDegrees: Long,
  val exifPolicy: ExifPolicyWire,
  val targetSizeBytes: Long? = null,
  /**
   * Only consulted by the WebP/HEIC native engines — JPEG/PNG compression
   * runs entirely in Dart and applies this itself before ever reaching a
   * platform channel.
   */
  val autoCorrectOrientation: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageCompressRequest {
      val taskId = pigeonVar_list[0] as String
      val sourcePath = pigeonVar_list[1] as String
      val outputPath = pigeonVar_list[2] as String?
      val format = pigeonVar_list[3] as ImageFormatWire?
      val quality = pigeonVar_list[4] as Long
      val maxWidth = pigeonVar_list[5] as Long?
      val maxHeight = pigeonVar_list[6] as Long?
      val rotationDegrees = pigeonVar_list[7] as Long
      val exifPolicy = pigeonVar_list[8] as ExifPolicyWire
      val targetSizeBytes = pigeonVar_list[9] as Long?
      val autoCorrectOrientation = pigeonVar_list[10] as Boolean
      return ImageCompressRequest(taskId, sourcePath, outputPath, format, quality, maxWidth, maxHeight, rotationDegrees, exifPolicy, targetSizeBytes, autoCorrectOrientation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taskId,
      sourcePath,
      outputPath,
      format,
      quality,
      maxWidth,
      maxHeight,
      rotationDegrees,
      exifPolicy,
      targetSizeBytes,
      autoCorrectOrientation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ImageCompressRequest
    return MessagesPigeonUtils.deepEquals(this.taskId, other.taskId) && MessagesPigeonUtils.deepEquals(this.sourcePath, other.sourcePath) && MessagesPigeonUtils.deepEquals(this.outputPath, other.outputPath) && MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.quality, other.quality) && MessagesPigeonUtils.deepEquals(this.maxWidth, other.maxWidth) && MessagesPigeonUtils.deepEquals(this.maxHeight, other.maxHeight) && MessagesPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && MessagesPigeonUtils.deepEquals(this.exifPolicy, other.exifPolicy) && MessagesPigeonUtils.deepEquals(this.targetSizeBytes, other.targetSizeBytes) && MessagesPigeonUtils.deepEquals(this.autoCorrectOrientation, other.autoCorrectOrientation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.taskId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourcePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.quality)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.exifPolicy)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.targetSizeBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.autoCorrectOrientation)
    return result
  }
  override fun toString(): String {
    return "ImageCompressRequest(taskId=$taskId, sourcePath=$sourcePath, outputPath=$outputPath, format=$format, quality=$quality, maxWidth=$maxWidth, maxHeight=$maxHeight, rotationDegrees=$rotationDegrees, exifPolicy=$exifPolicy, targetSizeBytes=$targetSizeBytes, autoCorrectOrientation=$autoCorrectOrientation)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoCompressRequest (
  val taskId: String,
  val sourcePath: String,
  val outputPath: String? = null,
  val preset: QualityPresetWire? = null,
  val codec: VideoCodecWire? = null,
  val maxWidth: Long? = null,
  val maxHeight: Long? = null,
  val fps: Long? = null,
  val bitrateBps: Long? = null,
  val audioEnabled: Boolean,
  val audioBitrateBps: Long? = null,
  val trimStartMs: Long? = null,
  val trimEndMs: Long? = null,
  val rotationDegrees: Long,
  val targetSizeBytes: Long? = null,
  val mode: CompressionModeWire
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoCompressRequest {
      val taskId = pigeonVar_list[0] as String
      val sourcePath = pigeonVar_list[1] as String
      val outputPath = pigeonVar_list[2] as String?
      val preset = pigeonVar_list[3] as QualityPresetWire?
      val codec = pigeonVar_list[4] as VideoCodecWire?
      val maxWidth = pigeonVar_list[5] as Long?
      val maxHeight = pigeonVar_list[6] as Long?
      val fps = pigeonVar_list[7] as Long?
      val bitrateBps = pigeonVar_list[8] as Long?
      val audioEnabled = pigeonVar_list[9] as Boolean
      val audioBitrateBps = pigeonVar_list[10] as Long?
      val trimStartMs = pigeonVar_list[11] as Long?
      val trimEndMs = pigeonVar_list[12] as Long?
      val rotationDegrees = pigeonVar_list[13] as Long
      val targetSizeBytes = pigeonVar_list[14] as Long?
      val mode = pigeonVar_list[15] as CompressionModeWire
      return VideoCompressRequest(taskId, sourcePath, outputPath, preset, codec, maxWidth, maxHeight, fps, bitrateBps, audioEnabled, audioBitrateBps, trimStartMs, trimEndMs, rotationDegrees, targetSizeBytes, mode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taskId,
      sourcePath,
      outputPath,
      preset,
      codec,
      maxWidth,
      maxHeight,
      fps,
      bitrateBps,
      audioEnabled,
      audioBitrateBps,
      trimStartMs,
      trimEndMs,
      rotationDegrees,
      targetSizeBytes,
      mode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoCompressRequest
    return MessagesPigeonUtils.deepEquals(this.taskId, other.taskId) && MessagesPigeonUtils.deepEquals(this.sourcePath, other.sourcePath) && MessagesPigeonUtils.deepEquals(this.outputPath, other.outputPath) && MessagesPigeonUtils.deepEquals(this.preset, other.preset) && MessagesPigeonUtils.deepEquals(this.codec, other.codec) && MessagesPigeonUtils.deepEquals(this.maxWidth, other.maxWidth) && MessagesPigeonUtils.deepEquals(this.maxHeight, other.maxHeight) && MessagesPigeonUtils.deepEquals(this.fps, other.fps) && MessagesPigeonUtils.deepEquals(this.bitrateBps, other.bitrateBps) && MessagesPigeonUtils.deepEquals(this.audioEnabled, other.audioEnabled) && MessagesPigeonUtils.deepEquals(this.audioBitrateBps, other.audioBitrateBps) && MessagesPigeonUtils.deepEquals(this.trimStartMs, other.trimStartMs) && MessagesPigeonUtils.deepEquals(this.trimEndMs, other.trimEndMs) && MessagesPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && MessagesPigeonUtils.deepEquals(this.targetSizeBytes, other.targetSizeBytes) && MessagesPigeonUtils.deepEquals(this.mode, other.mode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.taskId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourcePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.preset)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.codec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitrateBps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioEnabled)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioBitrateBps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.trimStartMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.trimEndMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.targetSizeBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mode)
    return result
  }
  override fun toString(): String {
    return "VideoCompressRequest(taskId=$taskId, sourcePath=$sourcePath, outputPath=$outputPath, preset=$preset, codec=$codec, maxWidth=$maxWidth, maxHeight=$maxHeight, fps=$fps, bitrateBps=$bitrateBps, audioEnabled=$audioEnabled, audioBitrateBps=$audioBitrateBps, trimStartMs=$trimStartMs, trimEndMs=$trimEndMs, rotationDegrees=$rotationDegrees, targetSizeBytes=$targetSizeBytes, mode=$mode)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ThumbnailRequest (
  val taskId: String,
  val sourcePath: String,
  /**
   * Validated Dart-side (against the source's real duration, from a
   * [MediaInfoRequest] pre-check) before this ever reaches native code —
   * out-of-range positions throw `InvalidMediaException` in Dart rather
   * than being handled by native bounds-checking.
   */
  val positionsMs: List<Long>,
  val maxWidth: Long,
  val maxHeight: Long,
  val format: ImageFormatWire,
  val quality: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ThumbnailRequest {
      val taskId = pigeonVar_list[0] as String
      val sourcePath = pigeonVar_list[1] as String
      val positionsMs = pigeonVar_list[2] as List<Long>
      val maxWidth = pigeonVar_list[3] as Long
      val maxHeight = pigeonVar_list[4] as Long
      val format = pigeonVar_list[5] as ImageFormatWire
      val quality = pigeonVar_list[6] as Long
      return ThumbnailRequest(taskId, sourcePath, positionsMs, maxWidth, maxHeight, format, quality)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taskId,
      sourcePath,
      positionsMs,
      maxWidth,
      maxHeight,
      format,
      quality,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ThumbnailRequest
    return MessagesPigeonUtils.deepEquals(this.taskId, other.taskId) && MessagesPigeonUtils.deepEquals(this.sourcePath, other.sourcePath) && MessagesPigeonUtils.deepEquals(this.positionsMs, other.positionsMs) && MessagesPigeonUtils.deepEquals(this.maxWidth, other.maxWidth) && MessagesPigeonUtils.deepEquals(this.maxHeight, other.maxHeight) && MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.quality, other.quality)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.taskId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourcePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.positionsMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxHeight)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.quality)
    return result
  }
  override fun toString(): String {
    return "ThumbnailRequest(taskId=$taskId, sourcePath=$sourcePath, positionsMs=$positionsMs, maxWidth=$maxWidth, maxHeight=$maxHeight, format=$format, quality=$quality)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaInfoRequest (
  val sourcePath: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfoRequest {
      val sourcePath = pigeonVar_list[0] as String
      return MediaInfoRequest(sourcePath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourcePath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaInfoRequest
    return MessagesPigeonUtils.deepEquals(this.sourcePath, other.sourcePath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourcePath)
    return result
  }
  override fun toString(): String {
    return "MediaInfoRequest(sourcePath=$sourcePath)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CompressionResultMessage (
  val outputPath: String,
  val originalSizeBytes: Long,
  val outputSizeBytes: Long,
  val compressionRatio: Double,
  val durationMs: Long,
  val codec: String,
  val format: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompressionResultMessage {
      val outputPath = pigeonVar_list[0] as String
      val originalSizeBytes = pigeonVar_list[1] as Long
      val outputSizeBytes = pigeonVar_list[2] as Long
      val compressionRatio = pigeonVar_list[3] as Double
      val durationMs = pigeonVar_list[4] as Long
      val codec = pigeonVar_list[5] as String
      val format = pigeonVar_list[6] as String
      return CompressionResultMessage(outputPath, originalSizeBytes, outputSizeBytes, compressionRatio, durationMs, codec, format)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outputPath,
      originalSizeBytes,
      outputSizeBytes,
      compressionRatio,
      durationMs,
      codec,
      format,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CompressionResultMessage
    return MessagesPigeonUtils.deepEquals(this.outputPath, other.outputPath) && MessagesPigeonUtils.deepEquals(this.originalSizeBytes, other.originalSizeBytes) && MessagesPigeonUtils.deepEquals(this.outputSizeBytes, other.outputSizeBytes) && MessagesPigeonUtils.deepEquals(this.compressionRatio, other.compressionRatio) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.codec, other.codec) && MessagesPigeonUtils.deepEquals(this.format, other.format)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.originalSizeBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputSizeBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.compressionRatio)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.codec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    return result
  }
  override fun toString(): String {
    return "CompressionResultMessage(outputPath=$outputPath, originalSizeBytes=$originalSizeBytes, outputSizeBytes=$outputSizeBytes, compressionRatio=$compressionRatio, durationMs=$durationMs, codec=$codec, format=$format)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ThumbnailResultMessage (
  val outputPath: String,
  val positionMs: Long,
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ThumbnailResultMessage {
      val outputPath = pigeonVar_list[0] as String
      val positionMs = pigeonVar_list[1] as Long
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      return ThumbnailResultMessage(outputPath, positionMs, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outputPath,
      positionMs,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ThumbnailResultMessage
    return MessagesPigeonUtils.deepEquals(this.outputPath, other.outputPath) && MessagesPigeonUtils.deepEquals(this.positionMs, other.positionMs) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.positionMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "ThumbnailResultMessage(outputPath=$outputPath, positionMs=$positionMs, width=$width, height=$height)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaInfoMessage (
  val mediaType: MediaTypeWire,
  val width: Long? = null,
  val height: Long? = null,
  val format: String? = null,
  val sizeBytes: Long,
  val exifPresent: Boolean? = null,
  val orientation: Long? = null,
  val durationMs: Long? = null,
  val fps: Double? = null,
  val bitrateBps: Long? = null,
  val videoCodec: String? = null,
  val audioCodec: String? = null,
  val container: String? = null,
  val hasAudio: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfoMessage {
      val mediaType = pigeonVar_list[0] as MediaTypeWire
      val width = pigeonVar_list[1] as Long?
      val height = pigeonVar_list[2] as Long?
      val format = pigeonVar_list[3] as String?
      val sizeBytes = pigeonVar_list[4] as Long
      val exifPresent = pigeonVar_list[5] as Boolean?
      val orientation = pigeonVar_list[6] as Long?
      val durationMs = pigeonVar_list[7] as Long?
      val fps = pigeonVar_list[8] as Double?
      val bitrateBps = pigeonVar_list[9] as Long?
      val videoCodec = pigeonVar_list[10] as String?
      val audioCodec = pigeonVar_list[11] as String?
      val container = pigeonVar_list[12] as String?
      val hasAudio = pigeonVar_list[13] as Boolean?
      return MediaInfoMessage(mediaType, width, height, format, sizeBytes, exifPresent, orientation, durationMs, fps, bitrateBps, videoCodec, audioCodec, container, hasAudio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaType,
      width,
      height,
      format,
      sizeBytes,
      exifPresent,
      orientation,
      durationMs,
      fps,
      bitrateBps,
      videoCodec,
      audioCodec,
      container,
      hasAudio,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaInfoMessage
    return MessagesPigeonUtils.deepEquals(this.mediaType, other.mediaType) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && MessagesPigeonUtils.deepEquals(this.exifPresent, other.exifPresent) && MessagesPigeonUtils.deepEquals(this.orientation, other.orientation) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.fps, other.fps) && MessagesPigeonUtils.deepEquals(this.bitrateBps, other.bitrateBps) && MessagesPigeonUtils.deepEquals(this.videoCodec, other.videoCodec) && MessagesPigeonUtils.deepEquals(this.audioCodec, other.audioCodec) && MessagesPigeonUtils.deepEquals(this.container, other.container) && MessagesPigeonUtils.deepEquals(this.hasAudio, other.hasAudio)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mediaType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.exifPresent)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.orientation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.fps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitrateBps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.videoCodec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audioCodec)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.container)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasAudio)
    return result
  }
  override fun toString(): String {
    return "MediaInfoMessage(mediaType=$mediaType, width=$width, height=$height, format=$format, sizeBytes=$sizeBytes, exifPresent=$exifPresent, orientation=$orientation, durationMs=$durationMs, fps=$fps, bitrateBps=$bitrateBps, videoCodec=$videoCodec, audioCodec=$audioCodec, container=$container, hasAudio=$hasAudio)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CapabilitiesReportMessage (
  val h264Encode: CodecSupportStatusWire,
  val hevcEncode: CodecSupportStatusWire,
  val aacEncode: CodecSupportStatusWire,
  val webpEncode: CodecSupportStatusWire,
  val heicEncode: CodecSupportStatusWire,
  val maxHardwareWidth: Long? = null,
  val maxHardwareHeight: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CapabilitiesReportMessage {
      val h264Encode = pigeonVar_list[0] as CodecSupportStatusWire
      val hevcEncode = pigeonVar_list[1] as CodecSupportStatusWire
      val aacEncode = pigeonVar_list[2] as CodecSupportStatusWire
      val webpEncode = pigeonVar_list[3] as CodecSupportStatusWire
      val heicEncode = pigeonVar_list[4] as CodecSupportStatusWire
      val maxHardwareWidth = pigeonVar_list[5] as Long?
      val maxHardwareHeight = pigeonVar_list[6] as Long?
      return CapabilitiesReportMessage(h264Encode, hevcEncode, aacEncode, webpEncode, heicEncode, maxHardwareWidth, maxHardwareHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      h264Encode,
      hevcEncode,
      aacEncode,
      webpEncode,
      heicEncode,
      maxHardwareWidth,
      maxHardwareHeight,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CapabilitiesReportMessage
    return MessagesPigeonUtils.deepEquals(this.h264Encode, other.h264Encode) && MessagesPigeonUtils.deepEquals(this.hevcEncode, other.hevcEncode) && MessagesPigeonUtils.deepEquals(this.aacEncode, other.aacEncode) && MessagesPigeonUtils.deepEquals(this.webpEncode, other.webpEncode) && MessagesPigeonUtils.deepEquals(this.heicEncode, other.heicEncode) && MessagesPigeonUtils.deepEquals(this.maxHardwareWidth, other.maxHardwareWidth) && MessagesPigeonUtils.deepEquals(this.maxHardwareHeight, other.maxHardwareHeight)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.h264Encode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hevcEncode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.aacEncode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.webpEncode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heicEncode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxHardwareWidth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxHardwareHeight)
    return result
  }
  override fun toString(): String {
    return "CapabilitiesReportMessage(h264Encode=$h264Encode, hevcEncode=$hevcEncode, aacEncode=$aacEncode, webpEncode=$webpEncode, heicEncode=$heicEncode, maxHardwareWidth=$maxHardwareWidth, maxHardwareHeight=$maxHardwareHeight)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProgressEventMessage (
  val taskId: String,
  val stage: CompressionStageWire,
  val percent: Double,
  val currentItemIndex: Long? = null,
  val totalItems: Long? = null,
  val note: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProgressEventMessage {
      val taskId = pigeonVar_list[0] as String
      val stage = pigeonVar_list[1] as CompressionStageWire
      val percent = pigeonVar_list[2] as Double
      val currentItemIndex = pigeonVar_list[3] as Long?
      val totalItems = pigeonVar_list[4] as Long?
      val note = pigeonVar_list[5] as String?
      return ProgressEventMessage(taskId, stage, percent, currentItemIndex, totalItems, note)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taskId,
      stage,
      percent,
      currentItemIndex,
      totalItems,
      note,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProgressEventMessage
    return MessagesPigeonUtils.deepEquals(this.taskId, other.taskId) && MessagesPigeonUtils.deepEquals(this.stage, other.stage) && MessagesPigeonUtils.deepEquals(this.percent, other.percent) && MessagesPigeonUtils.deepEquals(this.currentItemIndex, other.currentItemIndex) && MessagesPigeonUtils.deepEquals(this.totalItems, other.totalItems) && MessagesPigeonUtils.deepEquals(this.note, other.note)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.taskId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stage)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.percent)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.currentItemIndex)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.totalItems)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.note)
    return result
  }
  override fun toString(): String {
    return "ProgressEventMessage(taskId=$taskId, stage=$stage, percent=$percent, currentItemIndex=$currentItemIndex, totalItems=$totalItems, note=$note)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TaskTerminalMessage (
  val taskId: String,
  val outcome: TaskOutcomeWire,
  val result: CompressionResultMessage? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TaskTerminalMessage {
      val taskId = pigeonVar_list[0] as String
      val outcome = pigeonVar_list[1] as TaskOutcomeWire
      val result = pigeonVar_list[2] as CompressionResultMessage?
      val errorCode = pigeonVar_list[3] as String?
      val errorMessage = pigeonVar_list[4] as String?
      return TaskTerminalMessage(taskId, outcome, result, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      taskId,
      outcome,
      result,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TaskTerminalMessage
    return MessagesPigeonUtils.deepEquals(this.taskId, other.taskId) && MessagesPigeonUtils.deepEquals(this.outcome, other.outcome) && MessagesPigeonUtils.deepEquals(this.result, other.result) && MessagesPigeonUtils.deepEquals(this.errorCode, other.errorCode) && MessagesPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.taskId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outcome)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.result)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "TaskTerminalMessage(taskId=$taskId, outcome=$outcome, result=$result, errorCode=$errorCode, errorMessage=$errorMessage)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ImageFormatWire.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ExifPolicyWire.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          QualityPresetWire.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VideoCodecWire.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CompressionModeWire.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaTypeWire.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CodecSupportStatusWire.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CompressionStageWire.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TaskOutcomeWire.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageCompressRequest.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoCompressRequest.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ThumbnailRequest.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfoRequest.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompressionResultMessage.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ThumbnailResultMessage.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfoMessage.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CapabilitiesReportMessage.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProgressEventMessage.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TaskTerminalMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ImageFormatWire -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ExifPolicyWire -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is QualityPresetWire -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is VideoCodecWire -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is CompressionModeWire -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is MediaTypeWire -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is CodecSupportStatusWire -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is CompressionStageWire -> {
        stream.write(136)
        writeValue(stream, value.raw.toLong())
      }
      is TaskOutcomeWire -> {
        stream.write(137)
        writeValue(stream, value.raw.toLong())
      }
      is ImageCompressRequest -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is VideoCompressRequest -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is ThumbnailRequest -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is MediaInfoRequest -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is CompressionResultMessage -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is ThumbnailResultMessage -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is MediaInfoMessage -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is CapabilitiesReportMessage -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is ProgressEventMessage -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is TaskTerminalMessage -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ImageHostApi {
  fun compressImage(request: ImageCompressRequest, callback: (Result<CompressionResultMessage>) -> Unit)

  companion object {
    /** The codec used by ImageHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ImageHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ImageHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixel_compressor.ImageHostApi.compressImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ImageCompressRequest
            api.compressImage(requestArg) { result: Result<CompressionResultMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VideoHostApi {
  fun compressVideo(request: VideoCompressRequest, callback: (Result<CompressionResultMessage>) -> Unit)

  companion object {
    /** The codec used by VideoHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `VideoHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VideoHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixel_compressor.VideoHostApi.compressVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VideoCompressRequest
            api.compressVideo(requestArg) { result: Result<CompressionResultMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ThumbnailHostApi {
  fun generateThumbnails(request: ThumbnailRequest, callback: (Result<List<ThumbnailResultMessage>>) -> Unit)

  companion object {
    /** The codec used by ThumbnailHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ThumbnailHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ThumbnailHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixel_compressor.ThumbnailHostApi.generateThumbnails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ThumbnailRequest
            api.generateThumbnails(requestArg) { result: Result<List<ThumbnailResultMessage>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MetadataHostApi {
  fun getMediaInfo(request: MediaInfoRequest, callback: (Result<MediaInfoMessage>) -> Unit)

  companion object {
    /** The codec used by MetadataHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `MetadataHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MetadataHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixel_compressor.MetadataHostApi.getMediaInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as MediaInfoRequest
            api.getMediaInfo(requestArg) { result: Result<MediaInfoMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CapabilityHostApi {
  fun capabilities(callback: (Result<CapabilitiesReportMessage>) -> Unit)

  companion object {
    /** The codec used by CapabilityHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `CapabilityHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CapabilityHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixel_compressor.CapabilityHostApi.capabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.capabilities{ result: Result<CapabilitiesReportMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TaskHostApi {
  fun cancel(taskId: String, callback: (Result<Boolean>) -> Unit)
  fun cancelAll(callback: (Result<Unit>) -> Unit)
  fun activeTaskIds(callback: (Result<List<String>>) -> Unit)

  companion object {
    /** The codec used by TaskHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `TaskHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TaskHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixel_compressor.TaskHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            api.cancel(taskIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixel_compressor.TaskHostApi.cancelAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cancelAll{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pixel_compressor.TaskHostApi.activeTaskIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.activeTaskIds{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PixelCompressorProgressCallbackApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PixelCompressorProgressCallbackApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onProgress(eventArg: ProgressEventMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.pixel_compressor.PixelCompressorProgressCallbackApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onTaskTerminal(messageArg: TaskTerminalMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.pixel_compressor.PixelCompressorProgressCallbackApi.onTaskTerminal$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
