// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum ImageFormatWire { jpeg, png, webp, heic }

enum ExifPolicyWire { keep, strip }

enum QualityPresetWire { veryLow, low, medium, high, veryHigh, custom }

enum VideoCodecWire { h264, hevc, auto }

enum CompressionModeWire { manual, smart }

enum MediaTypeWire { image, video, unknown }

enum CodecSupportStatusWire { supported, unsupported, unknown }

enum CompressionStageWire {
  preparing,
  analyzing,
  decoding,
  encoding,
  muxing,
  finalizing,
  completed,
  failed,
  cancelled,
}

enum TaskOutcomeWire { completed, failed, cancelled }

class ImageCompressRequest {
  ImageCompressRequest({
    required this.taskId,
    required this.sourcePath,
    this.outputPath,
    this.format,
    required this.quality,
    this.maxWidth,
    this.maxHeight,
    required this.rotationDegrees,
    required this.exifPolicy,
    this.targetSizeBytes,
  });

  String taskId;

  String sourcePath;

  String? outputPath;

  ImageFormatWire? format;

  int quality;

  int? maxWidth;

  int? maxHeight;

  int rotationDegrees;

  ExifPolicyWire exifPolicy;

  int? targetSizeBytes;

  List<Object?> _toList() {
    return <Object?>[
      taskId,
      sourcePath,
      outputPath,
      format,
      quality,
      maxWidth,
      maxHeight,
      rotationDegrees,
      exifPolicy,
      targetSizeBytes,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ImageCompressRequest decode(Object result) {
    result as List<Object?>;
    return ImageCompressRequest(
      taskId: result[0]! as String,
      sourcePath: result[1]! as String,
      outputPath: result[2] as String?,
      format: result[3] as ImageFormatWire?,
      quality: result[4]! as int,
      maxWidth: result[5] as int?,
      maxHeight: result[6] as int?,
      rotationDegrees: result[7]! as int,
      exifPolicy: result[8]! as ExifPolicyWire,
      targetSizeBytes: result[9] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ImageCompressRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(taskId, other.taskId) &&
        _deepEquals(sourcePath, other.sourcePath) &&
        _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(format, other.format) &&
        _deepEquals(quality, other.quality) &&
        _deepEquals(maxWidth, other.maxWidth) &&
        _deepEquals(maxHeight, other.maxHeight) &&
        _deepEquals(rotationDegrees, other.rotationDegrees) &&
        _deepEquals(exifPolicy, other.exifPolicy) &&
        _deepEquals(targetSizeBytes, other.targetSizeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ImageCompressRequest(taskId: $taskId, sourcePath: $sourcePath, outputPath: $outputPath, format: $format, quality: $quality, maxWidth: $maxWidth, maxHeight: $maxHeight, rotationDegrees: $rotationDegrees, exifPolicy: $exifPolicy, targetSizeBytes: $targetSizeBytes)';
  }
}

class VideoCompressRequest {
  VideoCompressRequest({
    required this.taskId,
    required this.sourcePath,
    this.outputPath,
    this.preset,
    this.codec,
    this.maxWidth,
    this.maxHeight,
    this.fps,
    this.bitrateBps,
    required this.audioEnabled,
    this.audioBitrateBps,
    this.trimStartMs,
    this.trimEndMs,
    required this.rotationDegrees,
    this.targetSizeBytes,
    required this.mode,
  });

  String taskId;

  String sourcePath;

  String? outputPath;

  QualityPresetWire? preset;

  VideoCodecWire? codec;

  int? maxWidth;

  int? maxHeight;

  int? fps;

  int? bitrateBps;

  bool audioEnabled;

  int? audioBitrateBps;

  int? trimStartMs;

  int? trimEndMs;

  int rotationDegrees;

  int? targetSizeBytes;

  CompressionModeWire mode;

  List<Object?> _toList() {
    return <Object?>[
      taskId,
      sourcePath,
      outputPath,
      preset,
      codec,
      maxWidth,
      maxHeight,
      fps,
      bitrateBps,
      audioEnabled,
      audioBitrateBps,
      trimStartMs,
      trimEndMs,
      rotationDegrees,
      targetSizeBytes,
      mode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VideoCompressRequest decode(Object result) {
    result as List<Object?>;
    return VideoCompressRequest(
      taskId: result[0]! as String,
      sourcePath: result[1]! as String,
      outputPath: result[2] as String?,
      preset: result[3] as QualityPresetWire?,
      codec: result[4] as VideoCodecWire?,
      maxWidth: result[5] as int?,
      maxHeight: result[6] as int?,
      fps: result[7] as int?,
      bitrateBps: result[8] as int?,
      audioEnabled: result[9]! as bool,
      audioBitrateBps: result[10] as int?,
      trimStartMs: result[11] as int?,
      trimEndMs: result[12] as int?,
      rotationDegrees: result[13]! as int,
      targetSizeBytes: result[14] as int?,
      mode: result[15]! as CompressionModeWire,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoCompressRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(taskId, other.taskId) &&
        _deepEquals(sourcePath, other.sourcePath) &&
        _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(preset, other.preset) &&
        _deepEquals(codec, other.codec) &&
        _deepEquals(maxWidth, other.maxWidth) &&
        _deepEquals(maxHeight, other.maxHeight) &&
        _deepEquals(fps, other.fps) &&
        _deepEquals(bitrateBps, other.bitrateBps) &&
        _deepEquals(audioEnabled, other.audioEnabled) &&
        _deepEquals(audioBitrateBps, other.audioBitrateBps) &&
        _deepEquals(trimStartMs, other.trimStartMs) &&
        _deepEquals(trimEndMs, other.trimEndMs) &&
        _deepEquals(rotationDegrees, other.rotationDegrees) &&
        _deepEquals(targetSizeBytes, other.targetSizeBytes) &&
        _deepEquals(mode, other.mode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoCompressRequest(taskId: $taskId, sourcePath: $sourcePath, outputPath: $outputPath, preset: $preset, codec: $codec, maxWidth: $maxWidth, maxHeight: $maxHeight, fps: $fps, bitrateBps: $bitrateBps, audioEnabled: $audioEnabled, audioBitrateBps: $audioBitrateBps, trimStartMs: $trimStartMs, trimEndMs: $trimEndMs, rotationDegrees: $rotationDegrees, targetSizeBytes: $targetSizeBytes, mode: $mode)';
  }
}

class ThumbnailRequest {
  ThumbnailRequest({
    required this.taskId,
    required this.sourcePath,
    required this.positionsMs,
    required this.maxWidth,
    required this.maxHeight,
    required this.format,
    required this.quality,
  });

  String taskId;

  String sourcePath;

  /// Validated Dart-side (against the source's real duration, from a
  /// [MediaInfoRequest] pre-check) before this ever reaches native code —
  /// out-of-range positions throw `InvalidMediaException` in Dart rather
  /// than being handled by native bounds-checking.
  List<int> positionsMs;

  int maxWidth;

  int maxHeight;

  ImageFormatWire format;

  int quality;

  List<Object?> _toList() {
    return <Object?>[
      taskId,
      sourcePath,
      positionsMs,
      maxWidth,
      maxHeight,
      format,
      quality,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ThumbnailRequest decode(Object result) {
    result as List<Object?>;
    return ThumbnailRequest(
      taskId: result[0]! as String,
      sourcePath: result[1]! as String,
      positionsMs: (result[2]! as List<Object?>).cast<int>(),
      maxWidth: result[3]! as int,
      maxHeight: result[4]! as int,
      format: result[5]! as ImageFormatWire,
      quality: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ThumbnailRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(taskId, other.taskId) &&
        _deepEquals(sourcePath, other.sourcePath) &&
        _deepEquals(positionsMs, other.positionsMs) &&
        _deepEquals(maxWidth, other.maxWidth) &&
        _deepEquals(maxHeight, other.maxHeight) &&
        _deepEquals(format, other.format) &&
        _deepEquals(quality, other.quality);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ThumbnailRequest(taskId: $taskId, sourcePath: $sourcePath, positionsMs: $positionsMs, maxWidth: $maxWidth, maxHeight: $maxHeight, format: $format, quality: $quality)';
  }
}

class MediaInfoRequest {
  MediaInfoRequest({required this.sourcePath});

  String sourcePath;

  List<Object?> _toList() {
    return <Object?>[sourcePath];
  }

  Object encode() {
    return _toList();
  }

  static MediaInfoRequest decode(Object result) {
    result as List<Object?>;
    return MediaInfoRequest(sourcePath: result[0]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfoRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourcePath, other.sourcePath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaInfoRequest(sourcePath: $sourcePath)';
  }
}

class CompressionResultMessage {
  CompressionResultMessage({
    required this.outputPath,
    required this.originalSizeBytes,
    required this.outputSizeBytes,
    required this.compressionRatio,
    required this.durationMs,
    required this.codec,
    required this.format,
  });

  String outputPath;

  int originalSizeBytes;

  int outputSizeBytes;

  double compressionRatio;

  int durationMs;

  String codec;

  String format;

  List<Object?> _toList() {
    return <Object?>[
      outputPath,
      originalSizeBytes,
      outputSizeBytes,
      compressionRatio,
      durationMs,
      codec,
      format,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CompressionResultMessage decode(Object result) {
    result as List<Object?>;
    return CompressionResultMessage(
      outputPath: result[0]! as String,
      originalSizeBytes: result[1]! as int,
      outputSizeBytes: result[2]! as int,
      compressionRatio: result[3]! as double,
      durationMs: result[4]! as int,
      codec: result[5]! as String,
      format: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompressionResultMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(originalSizeBytes, other.originalSizeBytes) &&
        _deepEquals(outputSizeBytes, other.outputSizeBytes) &&
        _deepEquals(compressionRatio, other.compressionRatio) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(codec, other.codec) &&
        _deepEquals(format, other.format);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompressionResultMessage(outputPath: $outputPath, originalSizeBytes: $originalSizeBytes, outputSizeBytes: $outputSizeBytes, compressionRatio: $compressionRatio, durationMs: $durationMs, codec: $codec, format: $format)';
  }
}

class ThumbnailResultMessage {
  ThumbnailResultMessage({
    required this.outputPath,
    required this.positionMs,
    required this.width,
    required this.height,
  });

  String outputPath;

  int positionMs;

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[outputPath, positionMs, width, height];
  }

  Object encode() {
    return _toList();
  }

  static ThumbnailResultMessage decode(Object result) {
    result as List<Object?>;
    return ThumbnailResultMessage(
      outputPath: result[0]! as String,
      positionMs: result[1]! as int,
      width: result[2]! as int,
      height: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ThumbnailResultMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outputPath, other.outputPath) &&
        _deepEquals(positionMs, other.positionMs) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ThumbnailResultMessage(outputPath: $outputPath, positionMs: $positionMs, width: $width, height: $height)';
  }
}

class MediaInfoMessage {
  MediaInfoMessage({
    required this.mediaType,
    this.width,
    this.height,
    this.format,
    required this.sizeBytes,
    this.exifPresent,
    this.orientation,
    this.durationMs,
    this.fps,
    this.bitrateBps,
    this.videoCodec,
    this.audioCodec,
    this.container,
    this.hasAudio,
  });

  MediaTypeWire mediaType;

  int? width;

  int? height;

  String? format;

  int sizeBytes;

  bool? exifPresent;

  int? orientation;

  int? durationMs;

  double? fps;

  int? bitrateBps;

  String? videoCodec;

  String? audioCodec;

  String? container;

  bool? hasAudio;

  List<Object?> _toList() {
    return <Object?>[
      mediaType,
      width,
      height,
      format,
      sizeBytes,
      exifPresent,
      orientation,
      durationMs,
      fps,
      bitrateBps,
      videoCodec,
      audioCodec,
      container,
      hasAudio,
    ];
  }

  Object encode() {
    return _toList();
  }

  static MediaInfoMessage decode(Object result) {
    result as List<Object?>;
    return MediaInfoMessage(
      mediaType: result[0]! as MediaTypeWire,
      width: result[1] as int?,
      height: result[2] as int?,
      format: result[3] as String?,
      sizeBytes: result[4]! as int,
      exifPresent: result[5] as bool?,
      orientation: result[6] as int?,
      durationMs: result[7] as int?,
      fps: result[8] as double?,
      bitrateBps: result[9] as int?,
      videoCodec: result[10] as String?,
      audioCodec: result[11] as String?,
      container: result[12] as String?,
      hasAudio: result[13] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfoMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mediaType, other.mediaType) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(format, other.format) &&
        _deepEquals(sizeBytes, other.sizeBytes) &&
        _deepEquals(exifPresent, other.exifPresent) &&
        _deepEquals(orientation, other.orientation) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(fps, other.fps) &&
        _deepEquals(bitrateBps, other.bitrateBps) &&
        _deepEquals(videoCodec, other.videoCodec) &&
        _deepEquals(audioCodec, other.audioCodec) &&
        _deepEquals(container, other.container) &&
        _deepEquals(hasAudio, other.hasAudio);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaInfoMessage(mediaType: $mediaType, width: $width, height: $height, format: $format, sizeBytes: $sizeBytes, exifPresent: $exifPresent, orientation: $orientation, durationMs: $durationMs, fps: $fps, bitrateBps: $bitrateBps, videoCodec: $videoCodec, audioCodec: $audioCodec, container: $container, hasAudio: $hasAudio)';
  }
}

class CapabilitiesReportMessage {
  CapabilitiesReportMessage({
    required this.h264Encode,
    required this.hevcEncode,
    required this.aacEncode,
    required this.webpEncode,
    required this.heicEncode,
    this.maxHardwareWidth,
    this.maxHardwareHeight,
  });

  CodecSupportStatusWire h264Encode;

  CodecSupportStatusWire hevcEncode;

  CodecSupportStatusWire aacEncode;

  CodecSupportStatusWire webpEncode;

  CodecSupportStatusWire heicEncode;

  int? maxHardwareWidth;

  int? maxHardwareHeight;

  List<Object?> _toList() {
    return <Object?>[
      h264Encode,
      hevcEncode,
      aacEncode,
      webpEncode,
      heicEncode,
      maxHardwareWidth,
      maxHardwareHeight,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CapabilitiesReportMessage decode(Object result) {
    result as List<Object?>;
    return CapabilitiesReportMessage(
      h264Encode: result[0]! as CodecSupportStatusWire,
      hevcEncode: result[1]! as CodecSupportStatusWire,
      aacEncode: result[2]! as CodecSupportStatusWire,
      webpEncode: result[3]! as CodecSupportStatusWire,
      heicEncode: result[4]! as CodecSupportStatusWire,
      maxHardwareWidth: result[5] as int?,
      maxHardwareHeight: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CapabilitiesReportMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(h264Encode, other.h264Encode) &&
        _deepEquals(hevcEncode, other.hevcEncode) &&
        _deepEquals(aacEncode, other.aacEncode) &&
        _deepEquals(webpEncode, other.webpEncode) &&
        _deepEquals(heicEncode, other.heicEncode) &&
        _deepEquals(maxHardwareWidth, other.maxHardwareWidth) &&
        _deepEquals(maxHardwareHeight, other.maxHardwareHeight);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CapabilitiesReportMessage(h264Encode: $h264Encode, hevcEncode: $hevcEncode, aacEncode: $aacEncode, webpEncode: $webpEncode, heicEncode: $heicEncode, maxHardwareWidth: $maxHardwareWidth, maxHardwareHeight: $maxHardwareHeight)';
  }
}

class ProgressEventMessage {
  ProgressEventMessage({
    required this.taskId,
    required this.stage,
    required this.percent,
    this.currentItemIndex,
    this.totalItems,
    this.note,
  });

  String taskId;

  CompressionStageWire stage;

  double percent;

  int? currentItemIndex;

  int? totalItems;

  String? note;

  List<Object?> _toList() {
    return <Object?>[
      taskId,
      stage,
      percent,
      currentItemIndex,
      totalItems,
      note,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ProgressEventMessage decode(Object result) {
    result as List<Object?>;
    return ProgressEventMessage(
      taskId: result[0]! as String,
      stage: result[1]! as CompressionStageWire,
      percent: result[2]! as double,
      currentItemIndex: result[3] as int?,
      totalItems: result[4] as int?,
      note: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ProgressEventMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(taskId, other.taskId) &&
        _deepEquals(stage, other.stage) &&
        _deepEquals(percent, other.percent) &&
        _deepEquals(currentItemIndex, other.currentItemIndex) &&
        _deepEquals(totalItems, other.totalItems) &&
        _deepEquals(note, other.note);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ProgressEventMessage(taskId: $taskId, stage: $stage, percent: $percent, currentItemIndex: $currentItemIndex, totalItems: $totalItems, note: $note)';
  }
}

class TaskTerminalMessage {
  TaskTerminalMessage({
    required this.taskId,
    required this.outcome,
    this.result,
    this.errorCode,
    this.errorMessage,
  });

  String taskId;

  TaskOutcomeWire outcome;

  CompressionResultMessage? result;

  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[taskId, outcome, result, errorCode, errorMessage];
  }

  Object encode() {
    return _toList();
  }

  static TaskTerminalMessage decode(Object result) {
    result as List<Object?>;
    return TaskTerminalMessage(
      taskId: result[0]! as String,
      outcome: result[1]! as TaskOutcomeWire,
      result: result[2] as CompressionResultMessage?,
      errorCode: result[3] as String?,
      errorMessage: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TaskTerminalMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(taskId, other.taskId) &&
        _deepEquals(outcome, other.outcome) &&
        _deepEquals(result, other.result) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TaskTerminalMessage(taskId: $taskId, outcome: $outcome, result: $result, errorCode: $errorCode, errorMessage: $errorMessage)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ImageFormatWire) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ExifPolicyWire) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is QualityPresetWire) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is VideoCodecWire) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is CompressionModeWire) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is MediaTypeWire) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is CodecSupportStatusWire) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is CompressionStageWire) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    } else if (value is TaskOutcomeWire) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    } else if (value is ImageCompressRequest) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is VideoCompressRequest) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is ThumbnailRequest) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is MediaInfoRequest) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is CompressionResultMessage) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is ThumbnailResultMessage) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is MediaInfoMessage) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is CapabilitiesReportMessage) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is ProgressEventMessage) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is TaskTerminalMessage) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ImageFormatWire.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ExifPolicyWire.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : QualityPresetWire.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : VideoCodecWire.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : CompressionModeWire.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaTypeWire.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : CodecSupportStatusWire.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : CompressionStageWire.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : TaskOutcomeWire.values[value];
      case 138:
        return ImageCompressRequest.decode(readValue(buffer)!);
      case 139:
        return VideoCompressRequest.decode(readValue(buffer)!);
      case 140:
        return ThumbnailRequest.decode(readValue(buffer)!);
      case 141:
        return MediaInfoRequest.decode(readValue(buffer)!);
      case 142:
        return CompressionResultMessage.decode(readValue(buffer)!);
      case 143:
        return ThumbnailResultMessage.decode(readValue(buffer)!);
      case 144:
        return MediaInfoMessage.decode(readValue(buffer)!);
      case 145:
        return CapabilitiesReportMessage.decode(readValue(buffer)!);
      case 146:
        return ProgressEventMessage.decode(readValue(buffer)!);
      case 147:
        return TaskTerminalMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ImageHostApi {
  /// Constructor for [ImageHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ImageHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CompressionResultMessage> compressImage(
    ImageCompressRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.ImageHostApi.compressImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CompressionResultMessage;
  }
}

class VideoHostApi {
  /// Constructor for [VideoHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VideoHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CompressionResultMessage> compressVideo(
    VideoCompressRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.VideoHostApi.compressVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CompressionResultMessage;
  }
}

class ThumbnailHostApi {
  /// Constructor for [ThumbnailHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ThumbnailHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<ThumbnailResultMessage>> generateThumbnails(
    ThumbnailRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.ThumbnailHostApi.generateThumbnails$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<ThumbnailResultMessage>();
  }
}

class MetadataHostApi {
  /// Constructor for [MetadataHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MetadataHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<MediaInfoMessage> getMediaInfo(MediaInfoRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.MetadataHostApi.getMediaInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as MediaInfoMessage;
  }
}

class CapabilityHostApi {
  /// Constructor for [CapabilityHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CapabilityHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<CapabilitiesReportMessage> capabilities() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.CapabilityHostApi.capabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CapabilitiesReportMessage;
  }
}

class CacheHostApi {
  /// Constructor for [CacheHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CacheHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> clearCache() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.CacheHostApi.clearCache$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<int> getCacheSize() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.CacheHostApi.getCacheSize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }
}

class TaskHostApi {
  /// Constructor for [TaskHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TaskHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<bool> cancel(String taskId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.TaskHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[taskId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> cancelAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.TaskHostApi.cancelAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<String>> activeTaskIds() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.pixel_compressor.TaskHostApi.activeTaskIds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }
}

abstract class PixelCompressorProgressCallbackApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onProgress(ProgressEventMessage event);

  void onTaskTerminal(TaskTerminalMessage message);

  static void setUp(
    PixelCompressorProgressCallbackApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pixel_compressor.PixelCompressorProgressCallbackApi.onProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ProgressEventMessage arg_event =
              args[0]! as ProgressEventMessage;
          try {
            api.onProgress(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pixel_compressor.PixelCompressorProgressCallbackApi.onTaskTerminal$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final TaskTerminalMessage arg_message =
              args[0]! as TaskTerminalMessage;
          try {
            api.onTaskTerminal(arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
